version: "3.9"
services:
  asma-proto:
    image: localhost/asma-prototype:v0.0.6   # image is built on thar
    container_name: asma-proto
    network_mode: host                       # <-- avoids CNI/ports issues
    volumes:
      - /opt/shared/${USER}/asma-prototype/demo_data:/app/demo_data
      - /usr2/people/alex.styer/public_html:/app/alex_public_html:ro
    environment:
      - ASMA_DATA_DIR=/app/demo_data
      - ALEX_PUBLIC_HTML_DIR=/app/alex_public_html
    restart: unless-stopped
